from __future__ import annotations

import json
from pathlib import Path

import typer
import yaml
from rich.console import Console
from rich.table import Table

from edict.core.engine import Engine
from edict.core.loader import load_strategy_class
from edict.core.models import Bar
from edict.core.strategy import StrategyContext

app = typer.Typer(add_completion=False, no_args_is_help=True)
console = Console()

TEMPLATE_STRATEGY = """from __future__ import annotations

from typing import Any

from edict.core.models import Bar
from edict.core.strategy import Strategy


class {class_name}(Strategy):
    \"\"\"{class_name}: generated by edict.

    Implement your logic inside `on_bar`.
    Return a dict to emit a signal, or None to emit nothing.
    \"\"\"

    name = \"{strategy_name}\"

    def on_bar(self, bar: Bar) -> dict[str, Any] | None:
        # TODO: implement strategy logic
        return None
"""

TEMPLATE_TEST = """from edict.core.loader import load_strategy_class
from edict.core.strategy import Strategy


def test_load_{strategy_name}():
    cls = load_strategy_class(\"{module_path}:{class_name}\")
    assert issubclass(cls, Strategy)
"""

TEMPLATE_CONFIG = """symbol: BTCUSDT
timeframe: 1h
# strategy: {module_path}:{class_name}
"""


def _load_config(path: Path) -> dict:
    if not path.exists():
        raise typer.BadParameter(f"Config not found: {path}")
    with path.open("r", encoding="utf-8") as f:
        return yaml.safe_load(f) or {}


def _load_bars_from_jsonl(path: Path) -> list[Bar]:
    bars: list[Bar] = []
    with path.open("r", encoding="utf-8") as f:
        for line in f:
            line = line.strip()
            if not line:
                continue
            bars.append(Bar.model_validate_json(line))
    return bars


@app.command()
def strategies() -> None:
    """List built-in strategies."""
    table = Table(title="Built-in strategies")
    table.add_column("spec")
    table.add_column("name")
    from edict.strategies.demo import DemoStrategy

    items = [
        ("edict.strategies.demo:DemoStrategy", DemoStrategy.name),
    ]
    for spec, name in items:
        table.add_row(spec, name)
    console.print(table)


@app.command()
def new_strategy(
    name: str = typer.Argument(..., help="Strategy name, e.g. mean-reversion"),
    out_dir: Path = typer.Option(Path("."), "--out", help="Output directory"),
) -> None:
    """Generate a new strategy skeleton + test + config.

    Files created:
    - <out>/src/strategies/<name>.py
    - <out>/tests/test_<name>.py
    - <out>/configs/<name>.yaml

    Notes:
    - This command is project-agnostic: it generates a *strategy package* layout.
    - You can point `--out` to a new folder to start a fresh strategy repo.
    """

    import re

    safe = name.strip().lower().replace(" ", "-")
    if not re.fullmatch(r"[a-z0-9][a-z0-9\-]*", safe):
        raise typer.BadParameter(
            "Name must be kebab-case like 'mean-reversion' (letters/numbers/-)"
        )

    module_name = safe.replace("-", "_")
    class_name = "".join(part.capitalize() for part in safe.split("-")) + "Strategy"

    # strategy package layout
    pkg_root = out_dir
    src_dir = pkg_root / "src" / "strategies"
    tests_dir = pkg_root / "tests"
    cfg_dir = pkg_root / "configs"

    src_dir.mkdir(parents=True, exist_ok=True)
    tests_dir.mkdir(parents=True, exist_ok=True)
    cfg_dir.mkdir(parents=True, exist_ok=True)

    # Ensure python packages
    (pkg_root / "src").mkdir(parents=True, exist_ok=True)
    (pkg_root / "src" / "strategies").mkdir(parents=True, exist_ok=True)
    (pkg_root / "src" / "strategies" / "__init__.py").write_text("", encoding="utf-8")

    module_path = f"strategies.{module_name}"

    strategy_path = src_dir / f"{module_name}.py"
    test_path = tests_dir / f"test_{module_name}.py"
    config_path = cfg_dir / f"{module_name}.yaml"

    if strategy_path.exists() or test_path.exists() or config_path.exists():
        raise typer.BadParameter(
            "Target files already exist; choose another name or clean the output dir"
        )

    strategy_path.write_text(
        TEMPLATE_STRATEGY.format(class_name=class_name, strategy_name=safe),
        encoding="utf-8",
    )
    test_path.write_text(
        TEMPLATE_TEST.format(
            strategy_name=module_name,
            module_path=module_path,
            class_name=class_name,
        ),
        encoding="utf-8",
    )
    config_path.write_text(
        TEMPLATE_CONFIG.format(module_path=module_path, class_name=class_name),
        encoding="utf-8",
    )

    console.print("Generated:")
    console.print(f"- {strategy_path}")
    console.print(f"- {test_path}")
    console.print(f"- {config_path}")
    console.print("")
    console.print("Next steps (inside that project):")
    console.print("- ensure 'edict' is installed (or add it as a dependency)")
    console.print(f"- run: edict run --strategy {module_path}:{class_name} --config {config_path}")


@app.command()
def run(
    strategy: str = typer.Option(..., "--strategy", help="Strategy spec: module:ClassName"),
    config: Path = typer.Option(..., "--config", exists=False, help="YAML config path"),
    bars: Path | None = typer.Option(None, "--bars", help="Optional JSONL bars file"),
) -> None:
    """Run a strategy."""

    cfg = _load_config(config)
    symbol = str(cfg.get("symbol", "BTCUSDT"))
    timeframe = str(cfg.get("timeframe", "1h"))

    StrategyCls = load_strategy_class(strategy)
    ctx = StrategyContext(config=cfg, symbol=symbol, timeframe=timeframe)
    strat = StrategyCls(ctx)

    engine = Engine(console=console)

    # Demo bars when none provided
    if bars is None:
        demo = [
            Bar.model_validate(
                {
                    "ts": "2026-03-09T00:00:00Z",
                    "open": 66000,
                    "high": 66200,
                    "low": 65900,
                    "close": 66150,
                    "volume": 123.4,
                }
            ),
            Bar.model_validate(
                {
                    "ts": "2026-03-09T01:00:00Z",
                    "open": 66150,
                    "high": 66220,
                    "low": 65850,
                    "close": 65950,
                    "volume": 234.5,
                }
            ),
        ]
        bars_iter = demo
    else:
        bars_iter = _load_bars_from_jsonl(bars)

    signals = engine.run(strat, bars_iter)
    console.print(json.dumps({"signals": signals}, ensure_ascii=False, indent=2))
