from __future__ import annotations

import json
from pathlib import Path

import typer
import yaml
from rich.console import Console
from rich.table import Table

from edict.cli.templates import (
    TEMPLATE_GHA_CI,
    TEMPLATE_PROJECT_GITIGNORE,
    TEMPLATE_PROJECT_PYPROJECT,
    TEMPLATE_PROJECT_README,
)
from edict.core.doctor import run_doctor
from edict.core.engine import Engine
from edict.core.loader import load_strategy_class
from edict.core.models import Bar
from edict.core.strategy import StrategyContext

app = typer.Typer(add_completion=False, no_args_is_help=True)
console = Console()

TEMPLATE_STRATEGY = """from __future__ import annotations

from typing import Any

from edict.core.models import Bar
from edict.core.strategy import Strategy


class {class_name}(Strategy):
    \"\"\"{class_name}: generated by edict.

    Implement your logic inside `on_bar`.
    Return a dict to emit a signal, or None to emit nothing.
    \"\"\"

    name = \"{strategy_name}\"

    def on_bar(self, bar: Bar) -> dict[str, Any] | None:
        # TODO: implement strategy logic
        return None
"""

TEMPLATE_TEST = """from edict.core.loader import load_strategy_class
from edict.core.strategy import Strategy


def test_load_{strategy_name}():
    cls = load_strategy_class(\"{module_path}:{class_name}\")
    assert issubclass(cls, Strategy)
"""

TEMPLATE_CONFIG = """symbol: BTCUSDT
timeframe: 1h
strategy: {module_path}:{class_name}
"""


def _load_config(path: Path) -> dict:
    if not path.exists():
        raise typer.BadParameter(f"Config not found: {path}")
    with path.open("r", encoding="utf-8") as f:
        return yaml.safe_load(f) or {}


def _maybe_strategy_from_config(cfg: dict) -> str | None:
    val = cfg.get("strategy")
    if val is None:
        return None
    if not isinstance(val, str) or not val.strip():
        raise typer.BadParameter(
            "config.strategy must be a non-empty string like 'module:ClassName'"
        )
    return val.strip()


def _load_bars_from_jsonl(path: Path) -> list[Bar]:
    bars: list[Bar] = []
    with path.open("r", encoding="utf-8") as f:
        for line in f:
            line = line.strip()
            if not line:
                continue
            bars.append(Bar.model_validate_json(line))
    return bars


@app.command()
def tv_serve(
    host: str = typer.Option("0.0.0.0", "--host"),
    port: int = typer.Option(8787, "--port"),
) -> None:
    """Start TradingView webhook server.

    Env:
    - WECOM_WEBHOOK_URL: required
    - TV_WEBHOOK_SECRET: optional. If set, TradingView must send header X-TV-SECRET.

    Endpoint:
    - POST /tv/webhook
    """

    import uvicorn

    from edict.tv.server import create_app

    uvicorn.run(create_app(), host=host, port=port, log_level="info")


@app.command()
def caf_watch(
    poll_sec: int = typer.Option(15, "--poll-sec", help="Polling interval seconds"),
    include_ab: bool = typer.Option(
        True,
        "--ab",
        help="Include A+B: BTC/ETH and file top/bot rows",
    ),
) -> None:
    """Watch local CAF factor signals and push analysis to WeCom."""

    import asyncio

    from edict.tv.caf_watch import caf_watch as _caf_watch

    include_btc_eth = include_ab
    include_file_rows = include_ab

    asyncio.run(
        _caf_watch(
            include_btc_eth=include_btc_eth,
            include_file_rows=include_file_rows,
            poll_sec=poll_sec,
        )
    )


@app.command()
def hub_serve(
    host: str = typer.Option("127.0.0.1", "--host"),
    port: int = typer.Option(8790, "--port"),
) -> None:
    """Start local OpenClaw/edict status hub (HTML + JSON)."""

    import uvicorn

    from edict.hub.server import create_app

    uvicorn.run(create_app(), host=host, port=port, log_level="info")


@app.command()
def doctor(
    path: Path = typer.Argument(Path("."), help="Project path to inspect"),
) -> None:
    """Check the current project for common setup issues."""

    report = run_doctor(path.resolve())
    if report.ok:
        console.print("OK: project looks healthy")
        return

    console.print("Issues found:")
    for item in report.issues:
        console.print(f"- {item}")
    raise typer.Exit(code=1)


@app.command()
def strategies() -> None:
    """List built-in strategies."""
    table = Table(title="Built-in strategies")
    table.add_column("spec")
    table.add_column("name")
    from edict.strategies.demo import DemoStrategy

    items = [
        ("edict.strategies.demo:DemoStrategy", DemoStrategy.name),
    ]
    for spec, name in items:
        table.add_row(spec, name)
    console.print(table)


DEFAULT_OUT_DIR = Path(".")


@app.command()
def new_project(
    name: str = typer.Argument(..., help="Project folder name, e.g. my-btc-strategy"),
    out_dir: Path = typer.Option(DEFAULT_OUT_DIR, "--out", help="Parent output directory"),
    strategy: str = typer.Option("demo", "--strategy", help="Initial strategy name"),
) -> None:
    """Generate a new, runnable strategy project (Poetry + CI).

    This creates a standalone project folder with:
    - pyproject.toml
    - src/strategies/<strategy>.py
    - configs/<strategy>.yaml
    - tests/
    - .github/workflows/ci.yml

    After generation:
    ```bash
    cd <project>
    poetry install
    poetry run edict run --config configs/<strategy>.yaml
    ```
    """

    import re

    project = name.strip()
    if not project:
        raise typer.BadParameter("Project name cannot be empty")

    safe_strategy = strategy.strip().lower().replace(" ", "-")
    if not re.fullmatch(r"[a-z0-9][a-z0-9\-]*", safe_strategy):
        raise typer.BadParameter("Strategy name must be kebab-case")

    module_name = safe_strategy.replace("-", "_")
    class_name = "".join(part.capitalize() for part in safe_strategy.split("-")) + "Strategy"

    root = (out_dir / project).resolve()
    if root.exists() and any(root.iterdir()):
        raise typer.BadParameter(f"Target directory not empty: {root}")

    (root / ".github" / "workflows").mkdir(parents=True, exist_ok=True)
    (root / "src" / "strategies").mkdir(parents=True, exist_ok=True)
    (root / "configs").mkdir(parents=True, exist_ok=True)
    (root / "tests").mkdir(parents=True, exist_ok=True)

    # package init
    (root / "src" / "strategies" / "__init__.py").write_text("", encoding="utf-8")

    module_path = f"strategies.{module_name}"

    (root / "pyproject.toml").write_text(
        TEMPLATE_PROJECT_PYPROJECT.format(project_name=project),
        encoding="utf-8",
    )
    (root / "README.md").write_text(
        TEMPLATE_PROJECT_README.format(project_name=project, strategy_module=module_name),
        encoding="utf-8",
    )
    (root / ".gitignore").write_text(TEMPLATE_PROJECT_GITIGNORE, encoding="utf-8")
    (root / ".github" / "workflows" / "ci.yml").write_text(TEMPLATE_GHA_CI, encoding="utf-8")

    # strategy + config + test
    (root / "src" / "strategies" / f"{module_name}.py").write_text(
        TEMPLATE_STRATEGY.format(class_name=class_name, strategy_name=safe_strategy),
        encoding="utf-8",
    )
    (root / "configs" / f"{module_name}.yaml").write_text(
        TEMPLATE_CONFIG.format(module_path=module_path, class_name=class_name),
        encoding="utf-8",
    )
    (root / "tests" / f"test_{module_name}.py").write_text(
        TEMPLATE_TEST.format(
            strategy_name=module_name,
            module_path=module_path,
            class_name=class_name,
        ),
        encoding="utf-8",
    )

    console.print("Generated project:")
    console.print(f"- {root}")
    console.print("Next:")
    console.print(f"- cd {root}")
    console.print("- poetry install")
    console.print(f"- poetry run edict run --config configs/{module_name}.yaml")


@app.command()
def new_strategy(
    name: str = typer.Argument(..., help="Strategy name, e.g. mean-reversion"),
    out_dir: Path = typer.Option(DEFAULT_OUT_DIR, "--out", help="Output directory"),
) -> None:
    """Generate a new strategy skeleton + test + config.

    Files created:
    - <out>/src/strategies/<name>.py
    - <out>/tests/test_<name>.py
    - <out>/configs/<name>.yaml

    Notes:
    - This command is project-agnostic: it generates a *strategy package* layout.
    - You can point `--out` to a new folder to start a fresh strategy repo.
    """

    import re

    safe = name.strip().lower().replace(" ", "-")
    if not re.fullmatch(r"[a-z0-9][a-z0-9\-]*", safe):
        raise typer.BadParameter(
            "Name must be kebab-case like 'mean-reversion' (letters/numbers/-)"
        )

    module_name = safe.replace("-", "_")
    class_name = "".join(part.capitalize() for part in safe.split("-")) + "Strategy"

    # strategy package layout
    pkg_root = out_dir
    src_dir = pkg_root / "src" / "strategies"
    tests_dir = pkg_root / "tests"
    cfg_dir = pkg_root / "configs"

    src_dir.mkdir(parents=True, exist_ok=True)
    tests_dir.mkdir(parents=True, exist_ok=True)
    cfg_dir.mkdir(parents=True, exist_ok=True)

    # Ensure python packages
    (pkg_root / "src").mkdir(parents=True, exist_ok=True)
    (pkg_root / "src" / "strategies").mkdir(parents=True, exist_ok=True)
    (pkg_root / "src" / "strategies" / "__init__.py").write_text("", encoding="utf-8")

    module_path = f"strategies.{module_name}"

    strategy_path = src_dir / f"{module_name}.py"
    test_path = tests_dir / f"test_{module_name}.py"
    config_path = cfg_dir / f"{module_name}.yaml"

    if strategy_path.exists() or test_path.exists() or config_path.exists():
        raise typer.BadParameter(
            "Target files already exist; choose another name or clean the output dir"
        )

    strategy_path.write_text(
        TEMPLATE_STRATEGY.format(class_name=class_name, strategy_name=safe),
        encoding="utf-8",
    )
    test_path.write_text(
        TEMPLATE_TEST.format(
            strategy_name=module_name,
            module_path=module_path,
            class_name=class_name,
        ),
        encoding="utf-8",
    )
    config_path.write_text(
        TEMPLATE_CONFIG.format(module_path=module_path, class_name=class_name),
        encoding="utf-8",
    )

    console.print("Generated:")
    console.print(f"- {strategy_path}")
    console.print(f"- {test_path}")
    console.print(f"- {config_path}")
    console.print("")
    console.print("Next steps (inside that project):")
    console.print("- ensure 'edict' is installed (or add it as a dependency)")
    console.print(f"- add to config: strategy: {module_path}:{class_name}")
    console.print(f"- run: edict run --config {config_path}")


@app.command()
def run(
    strategy: str | None = typer.Option(
        None,
        "--strategy",
        help="Strategy spec: module:ClassName (optional if config has 'strategy: ...')",
    ),
    config: Path = typer.Option(..., "--config", exists=False, help="YAML config path"),
    bars: Path | None = typer.Option(None, "--bars", help="Optional JSONL bars file"),
) -> None:
    """Run a strategy."""

    cfg = _load_config(config)
    symbol = str(cfg.get("symbol", "BTCUSDT"))
    timeframe = str(cfg.get("timeframe", "1h"))

    strategy_spec = strategy or _maybe_strategy_from_config(cfg)
    if strategy_spec is None:
        raise typer.BadParameter(
            "Missing strategy. Provide --strategy module:ClassName or set config.strategy"
        )

    StrategyCls = load_strategy_class(strategy_spec)
    ctx = StrategyContext(config=cfg, symbol=symbol, timeframe=timeframe)
    strat = StrategyCls(ctx)

    engine = Engine(console=console)

    # Demo bars when none provided
    if bars is None:
        demo = [
            Bar.model_validate(
                {
                    "ts": "2026-03-09T00:00:00Z",
                    "open": 66000,
                    "high": 66200,
                    "low": 65900,
                    "close": 66150,
                    "volume": 123.4,
                }
            ),
            Bar.model_validate(
                {
                    "ts": "2026-03-09T01:00:00Z",
                    "open": 66150,
                    "high": 66220,
                    "low": 65850,
                    "close": 65950,
                    "volume": 234.5,
                }
            ),
        ]
        bars_iter = demo
    else:
        bars_iter = _load_bars_from_jsonl(bars)

    signals = engine.run(strat, bars_iter)
    console.print(json.dumps({"signals": signals}, ensure_ascii=False, indent=2))
