from __future__ import annotations

# Pure string templates used by CLI generators.

TEMPLATE_PROJECT_PYPROJECT = """[project]
name = \"{project_name}\"
version = \"0.1.0\"
description = \"EDICT strategy project\"
requires-python = \">=3.10,<4.0\"
dependencies = [
  \"edict\",
]

[dependency-groups]
dev = [
  \"pytest>=8,<10\",
  \"ruff>=0.6,<1\",
]

[tool.ruff]
line-length = 100

[tool.ruff.lint]
select = [\"E\", \"F\", \"I\", \"B\", \"UP\"]

[tool.pytest.ini_options]
testpaths = [\"tests\"]

[build-system]
requires = [\"poetry-core>=2.0.0,<3.0.0\"]
build-backend = \"poetry.core.masonry.api\"
"""

TEMPLATE_PROJECT_README = """# {project_name}

Strategy project generated by **edict**.

## Setup

```bash
poetry install
```

## Run

```bash
poetry run edict run --config configs/{strategy_module}.yaml
```

## Test

```bash
poetry run ruff check .
poetry run pytest -q
```
"""

TEMPLATE_PROJECT_GITIGNORE = """__pycache__/
*.py[cod]
*.egg-info/
dist/
build/
.venv/
.env
.pytest_cache/
.ruff_cache/
.DS_Store
"""

TEMPLATE_GHA_CI = """name: ci
on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Install poetry
        run: pipx install poetry
      - name: Install deps
        run: poetry install
      - name: Lint
        run: poetry run ruff check .
      - name: Tests
        run: poetry run pytest -q
"""
